const { VITE_ACCESS_TOKEN, VITE_REFRESH_TOKEN, VITE_USER_DATA_OBJECT } = import.meta.env;

export {
    VITE_ACCESS_TOKEN       as ACCESS_TOKEN,
    VITE_REFRESH_TOKEN      as REFRESH_TOKEN, 
    VITE_USER_DATA_OBJECT   as USER_DATA_OBJECT,
};